<?php

return [
    'cv_path' => 'cv/V-Cyril-Darivs-Egipto-Resume.pdf',

    'projects' => [
        [
            'name' => 'ErgoVision',
            'tagline' => 'AI posture correction',
            'subtitle' => 'Angle-based scoring and adaptive feedback',
            'description' => 'An AI-powered posture correction system that uses MediaPipe pose estimation to track body angles in real time. Scores ergonomic alignment with an angle-based engine and delivers adaptive feedback to help users fix desk posture — backed by a Laravel + Vue.js dashboard, Python ML pipeline, and MySQL database.',
            'tags' => ['Python', 'MediaPipe', 'OpenCV', 'Laravel', 'Vue.js', 'MySQL', 'REST API', 'Tailwind CSS'],
            'accent' => 'teal',
            'image' => 'images/projects/ergovision.png',
            'image_fit' => 'contain',
            'image_position' => 'top center',
            'featured' => true,
            'live' => 'https://www.ergovision.online',
            'github' => 'https://github.com/v-cyril/ergovision',
        ],
        [
            'name' => 'JobHunterAI',
            'tagline' => 'AI career assistant',
            'subtitle' => 'Resume-aware scoring, ranking & job tracking',
            'description' => 'An AI-powered job hunting pipeline that scrapes remote listings from multiple sources, scores and ranks them against a developer profile using OpenAI, and tracks every application in a drag-and-drop Kanban dashboard. Features Telegram notifications, SQLite persistence, and a background scheduler for fully automated daily scans.',
            'tags' => ['Python', 'OpenAI API', 'Flask', 'SQLite', 'Docker', 'Web Scraping', 'Telegram Bot', 'HuggingFace'],
            'accent' => 'sky',
            'image' => 'images/projects/jobhunterai.png',
            'image_fit' => 'contain',
            'image_position' => 'top center',
            'featured' => true,
            'live' => 'https://huggingface.co/spaces/Darivsxp/JobHunterAI',
            'github' => 'https://github.com/DarivsXP/jobhunterAI',
        ],
        [
            'name' => 'VertexShop',
            'tagline' => 'E-commerce platform',
            'description' => 'A full-stack e-commerce platform with user authentication, product catalog, cart, wishlist, mock checkout, and order tracking. Includes an admin dashboard for inventory and orders, REST APIs with Laravel Sanctum, and a responsive Vue.js storefront.',
            'tags' => ['Laravel', 'Vue.js', 'MySQL', 'Sanctum', 'REST API', 'Tailwind CSS'],
            'accent' => 'violet',
            'image' => 'images/projects/vertexshop.png',
            'featured' => true,
            'live' => 'https://vertexshop.cyrilegipto.space',
            'github' => 'https://github.com/DarivsXP/VertexShop',
        ],
        [
            'name' => "Nathalie's Bakeshop",
            'tagline' => 'In progress',
            'subtitle' => 'Client bakeshop platform',
            'description' => 'A Laravel + React web application in active development for a local bakeshop client. Built around product showcases, ordering flows, and an admin-friendly structure so the owner can update menus and specials with ease — warm, mobile-first, and designed to convert casual browsers into repeat customers.',
            'tags' => ['Laravel', 'React', 'MySQL', 'REST API', 'Tailwind CSS'],
            'accent' => 'amber',
            'image' => 'images/projects/nathaliesbakeshop.png',
            'featured' => false,
            'live' => 'https://nathaliesbakeshop.cyrilegipto.space',
            'github' => 'https://github.com/DarivsXP/nathaliesbakeshop',
        ],
        [
            'name' => 'Your Offshore Accountant',
            'tagline' => 'Client project',
            'subtitle' => 'Bookkeeping services for US & Canadian firms',
            'description' => 'A professional marketing site built for an offshore accounting firm offering personalized, cost-effective bookkeeping to US and Canadian teams. Crafted with semantic HTML5 and Bootstrap 5 — service pages, clear CTAs, and a polished brand presence the client loved from day one.',
            'tags' => ['HTML5', 'Bootstrap 5', 'CSS3', 'JavaScript', 'Responsive Design'],
            'accent' => 'rose',
            'image' => 'images/projects/youroffshoreaccountant.png',
            'image_fit' => 'cover',
            'image_position' => 'top center',
            'featured' => false,
            'live' => 'https://youroffshoreaccountant.com',
            'github' => null,
        ],
    ],

    'skills' => [
        // Top 6 — these appear as orbit satellites (keep names short)
        ['name' => 'PHP',            'color' => '#8b5cf6'],
        ['name' => 'Python',         'color' => '#fbbf24'],
        ['name' => 'Laravel',        'color' => '#f87171'],
        ['name' => 'Vue.js',         'color' => '#34d399'],
        ['name' => 'React',          'color' => '#38bdf8'],
        ['name' => 'MySQL',          'color' => '#2dd4bf'],
        // Rest scroll in the stack banner
        ['name' => 'JavaScript',     'color' => '#facc15'],
        ['name' => 'TypeScript',     'color' => '#60a5fa'],
        ['name' => 'C',              'color' => '#94a3b8'],
        ['name' => 'C++',            'color' => '#6b9dcf'],
        ['name' => 'Node.js',        'color' => '#4ade80'],
        ['name' => 'Bootstrap',      'color' => '#a78bfa'],
        ['name' => 'Tailwind CSS',   'color' => '#5eead4'],
        ['name' => 'PostgreSQL',     'color' => '#818cf8'],
        ['name' => 'RESTful APIs',   'color' => '#fb923c'],
        ['name' => 'WebSockets',     'color' => '#10b981'],
        ['name' => 'Firebase',       'color' => '#fbbf24'],
        ['name' => 'Git',            'color' => '#f472b6'],
        ['name' => 'GitHub',         'color' => '#a78bfa'],
        ['name' => 'Docker',         'color' => '#22d3ee'],
        ['name' => 'Postman',        'color' => '#ff6c37'],
        ['name' => 'npm',            'color' => '#cb3837'],
        ['name' => 'Composer',       'color' => '#f0b88a'],
        ['name' => 'Vite',           'color' => '#c084fc'],
        ['name' => 'Sanctum',        'color' => '#f0b88a'],
        ['name' => 'CI/CD',          'color' => '#4ade80'],
        ['name' => 'OOP',            'color' => '#94a3b8'],
        ['name' => 'MVC',            'color' => '#e879f9'],
    ],

    'hero_roles' => [
        'Full-Stack Developer',
        'Laravel Engineer',
        'Vue.js Builder',
        'API Architect',
        'Python Developer',
    ],
];
